import type { Config } from "tailwindcss";

// Konfigurasi shadcn/ui-ready (CSS variables theme). Tambah komponen via `npx shadcn@latest add ...`.
const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },

        // ── Palet Material (dipakai landing page redesign) ──
        "surface-container-low": "#f3f3f4",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e8e8e9",
        surface: "#f9f9fa",
        "surface-bright": "#f9f9fa",
        outline: "#6e7977",
        "on-primary-container": "#a3faef",
        "tertiary-fixed": "#dce2f7",
        "secondary-fixed-dim": "#ffb690",
        "surface-container-highest": "#e2e2e3",
        "on-primary": "#ffffff",
        "on-surface": "#1a1c1d",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffdbca",
        "surface-container": "#eeeeef",
        "tertiary-fixed-dim": "#c0c6db",
        "on-tertiary": "#ffffff",
        "surface-dim": "#dadadb",
        "on-secondary-fixed-variant": "#783200",
        "on-primary-fixed": "#00201d",
        "teal-dark": "#134E4A",
        "primary-fixed": "#9cf2e8",
        "on-surface-variant": "#3e4947",
        "on-primary-fixed-variant": "#00504a",
        "primary-fixed-dim": "#80d5cb",
        "surface-tint": "#006a63",
        "inverse-on-surface": "#f0f1f2",
        "zinc-dark": "#18181B",
        "on-tertiary-fixed": "#141b2b",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3132",
        "teal-light": "#F0FDFA",
        tertiary: "#4a5162",
        "on-secondary-container": "#5c2400",
        "primary-container": "#0f766e",
        primary: "#005c55",
        "tertiary-container": "#62697b",
        "on-tertiary-fixed-variant": "#404758",
        "inverse-primary": "#80d5cb",
        "on-secondary": "#ffffff",
        "zinc-muted": "#52525B",
        "on-background": "#1a1c1d",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#341100",
        "surface-variant": "#e2e2e3",
        error: "#ba1a1a",
        "on-tertiary-container": "#e3e9ff",
        "secondary-container": "#fd761a",
        "outline-variant": "#bdc9c6",
        secondary: "#9d4300",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      maxWidth: {
        "max-width": "1280px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        gutter: "24px",
        base: "4px",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        "table-data": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "table-data": ["14px", { lineHeight: "1.4", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "1", letterSpacing: "0.02em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
